export const REQUEST_EXCHANGE_RATE = 'REQUEST_EXCHANGE_RATE';
export const REQUEST_EXCHANGE_RATE_SUCCESS = 'REQUEST_EXCHANGE_RATE_SUCCESS';
export const REQUEST_EXCHANGE_RATE_FAILURE = 'REQUEST_EXCHANGE_RATE_FAILURE';

export const sendExpenses = (payload) => ({
  type: REQUEST_EXCHANGE_RATE_SUCCESS,
  payload,
});
